services:
  mysql:
    image: mysql:8.0
    container_name: ues-mysql-dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-dev-data:/var/lib/mysql
    networks:
      - ues-network-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio
    container_name: ues-minio-dev
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-dev-data:/data
    command: server /data --console-address ":9090"
    networks:
      - ues-network-dev

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: ues-elasticsearch-dev
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es-dev-data:/usr/share/elasticsearch/data
    networks:
      - ues-network-dev

volumes:
  mysql-dev-data:
  minio-dev-data:
  es-dev-data:

networks:
  ues-network-dev:
    driver: bridge
